"""Generate the CGH2 datasets (reference configuration, not a verified Saudi system).

    python scripts/cgh2_generate.py                       # medium (main) + low and high (out-of-distribution) -> output/cgh2/{medium,low,high}/
    python scripts/cgh2_generate.py --class medium         # one class
    python scripts/cgh2_generate.py --fast                 # smoke test (5-day episodes, one variant per family)
    python scripts/cgh2_generate.py --sample               # the small committed sample -> samples/cgh2/
    python scripts/cgh2_generate.py --h2-mode spec --flow-mode spec      # workbook Sec. 9 instruments
    python scripts/cgh2_generate.py --no-valve-states      # ablation: compressor status and valve states hidden from the dashboard
    python scripts/cgh2_generate.py --no-historian         # ideal instrument data

The same via the system switch: python scripts/generate_physical_dataset.py --system cgh2 (default stays lh2). Generated data stays out of git.
"""

import argparse
import os
import sys
from dataclasses import replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from hydrai_twin.cgh2.dataset import OOD_MODULES, CGH2DatasetConfig, cgh2_historian, generate_cgh2_dataset

ROOT = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", choices=["medium", "low", "high", "all"], default="all")
    ap.add_argument("--fast", action="store_true")
    ap.add_argument("--sample", action="store_true", help="small committed sample -> samples/cgh2/")
    ap.add_argument("--h2-mode", choices=["lfl", "spec"], default="lfl")
    ap.add_argument("--flow-mode", choices=["datasheet", "spec"], default="datasheet")
    ap.add_argument("--no-valve-states", action="store_true")
    ap.add_argument("--no-historian", action="store_true")
    ap.add_argument("--prv-blowdown", choices=["nominal", "conservative"], default="nominal")
    ap.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    common = dict(h2_mode=args.h2_mode, flow_mode=args.flow_mode, valve_states=not args.no_valve_states, prv_blowdown=args.prv_blowdown,
                  historian=cgh2_historian(not args.no_historian))
    base = ROOT / (args.out or ("samples/cgh2" if args.sample else "output/cgh2" + ("_fast" if args.fast else "")))
    if args.sample:
        cfg = CGH2DatasetConfig(pressure_class="medium", roles="main", dev_modules=("M01",), include_unseen=False, include_commissioning=False, fast=True,
                                include_rupture=True, **common)
        # three short episodes: a healthy run, a compressor overrun (relief lifting) and a rupture
        import hydrai_twin.cgh2.dataset as D
        keep = {"normal-refuelling0", "pressure-compressor_overrun", "rupture-50mm"}
        jobs = [j for j in D.build_jobs(cfg, base) if j.variant.key in keep]
        for j in jobs:
            j.overrides = {**j.overrides, "days": 4.0, "onset_day_range": (1.0, 2.0)}
        entries = [D.run_job(j) for j in jobs]
        import json
        for e in entries:
            for k in [k for k in e if k.startswith("_")]:
                e.pop(k)
        (base / "manifest.json").write_text(json.dumps({"system": "cgh2", "dashboard_label": "reference configuration, not a verified Saudi system",
                                                        "note": "small committed sample (4-day episodes, medium class); the full datasets are generated by scripts/cgh2_generate.py",
                                                        "episodes": entries}, indent=1, default=str))
        size = sum(f.stat().st_size for f in base.rglob("*") if f.is_file()) / 1e6
        print(f"wrote {len(entries)} sample episodes to {base} ({size:.1f} MB)")
        return
    classes = ["medium", "low", "high"] if args.cls == "all" else [args.cls]
    for c in classes:
        if c == "medium":
            cfg = CGH2DatasetConfig(pressure_class="medium", fast=args.fast, **common)
        else:
            cfg = CGH2DatasetConfig(pressure_class=c, roles="ood", dev_modules=OOD_MODULES, include_unseen=False, fast=args.fast, reduced=True, **common)
        out = base / c
        print(f"writing {out} (class {c}, workers={args.workers}, fast={cfg.fast}, h2={cfg.h2_mode}, flow={cfg.flow_mode}, valve states={cfg.valve_states}, historian={'on' if cfg.historian.enabled else 'off'})")
        m = generate_cgh2_dataset(cfg, out, workers=args.workers)
        by = {}
        for e in m["episodes"]:
            by[e["role"]] = by.get(e["role"], 0) + 1
        print(f"  {m['n_episodes']} episodes {by} in {m['wall_seconds']} s")


if __name__ == "__main__":
    main()
