"""Write CGH2_REGISTRY.md: every CGH2 parameter with its value, source tag and basis, the placeholders, and the register/addendum conflicts.

    python scripts/cgh2_registry_doc.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from hydrai_twin.cgh2 import registry as R

ROOT = Path(__file__).resolve().parent.parent


def fmt(v):
    return str(v) if not isinstance(v, float) else f"{v:g}"


def main():
    lines = ["# CGH2 parameter registry", "",
             "Generated by `scripts/cgh2_registry_doc.py` from `hydrai_twin/cgh2/registry.py`. **Reference configuration, not a verified Saudi system.**", "",
             "**The decision register file was NOT available when the CGH2 twin was built** (only Addendum 1 and the build instruction). Values the register would define",
             "and that the instruction or addendum do not give (its Sec. 5 tag table, per-class thermal constants, the section-2 conflicts) are defaults tagged JUDGE; values",
             "relayed in the instruction as 'from the register' are tagged REG-UNREAD. **Everything tagged U, JUDGE or REG-UNREAD is a flagged placeholder.**", "",
             "Tags: V1 read at the primary document or datasheet (via a fetch tool that summarises PDFs: spot-check before quoting); V2 reputable secondary; V3 existence only;",
             "U not found; CALC our calculation; JUDGE decision without a source; REG-UNREAD relayed from the register, unread.", ""]
    counts = {}
    for e in R.REGISTRY.values():
        counts[e.tag] = counts.get(e.tag, 0) + 1
    lines += ["| tag | entries |", "|---|---|"] + [f"| {t} | {counts.get(t, 0)} |" for t in R.TAGS] + [""]
    lines += ["## Entries", "", "| name | value | unit | tag | source / basis |", "|---|---|---|---|---|"]
    for e in R.REGISTRY.values():
        basis = (e.source + (f" — {e.basis}" if e.basis else "")).replace("|", "/")
        lines.append(f"| `{e.name}` | {fmt(e.value)} | {e.unit} | {e.tag}{' (placeholder)' if e.is_placeholder else ''} | {basis} |")
    lines += ["", "## Conflicts resolved (register / instruction vs Addendum 1, and findings of the verification checks)", "",
              "| entry | resolved as | tag | source |", "|---|---|---|---|"]
    for c in R.conflicts():
        lines.append(f"| `{c['name']}` | {c['resolved_as']} | {c['tag']} | {c['source'][:80].replace('|', '/')} |")
    (ROOT / "CGH2_REGISTRY.md").write_text("\n".join(lines) + "\n")
    print(f"wrote CGH2_REGISTRY.md ({len(R.REGISTRY)} entries, {sum(e.is_placeholder for e in R.REGISTRY.values())} placeholders, {len(R.conflicts())} conflicts)")


if __name__ == "__main__":
    main()
